/* Owned wasm load, select history, search, play, save and reload. */
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const files=['DATA/0_0.bin','ZERO/0_0.bin','DREL/0_0.bin','prfs/0_0.bin','PATB/0_entries.bin','ESTR/0_pattern_strings.bin','EXPR/0_full.bin','FRST/0_0.bin',...Array.from('?abcdefghijklmnopqrstuvwxyz',c=>`MUL${c}/0_0.bin`),...Array.from('abcdefgh',c=>`VCB${c}/0_0.bin`)];
const blobs=files.map(p=>fs.readFileSync(`resources/${p}`)),packet=Buffer.alloc(43*8+blobs.reduce((n,b)=>n+b.length,0));let offset=43*8;blobs.forEach((b,i)=>{packet.writeUInt32BE(offset,8*i);packet.writeUInt32BE(b.length,8*i+4);b.copy(packet,offset);offset+=b.length;});
const dictionary=fs.readFileSync('../../media/maven/session/share/maven2.1'),wasm=fs.readFileSync('.build/maven-portable.wasm');const {instance}=await WebAssembly.instantiate(wasm,{}),e=instance.exports;
const view=id=>new Uint8Array(e.memory.buffer,e.maven_port_buffer(id),e.maven_port_capacity(id));const write=(id,b)=>{assert(b.length<=view(id).length);view(id).set(b);};const read=(id,n)=>Buffer.from(view(id).slice(0,n));const be32=x=>{const b=Buffer.alloc(4);b.writeUInt32BE(x>>>0);return b;};
write(0,packet);write(1,dictionary);assert.equal(e.maven_port_create(packet.length,dictionary.length),0);view(0).fill(0);view(1).fill(0);
const history=JSON.parse(fs.readFileSync('analysis/toolchain/history-continued-end6-live.json')),turn=JSON.parse(fs.readFileSync('analysis/toolchain/turn-commit-burin-fresh-live.json'));assert(history.complete&&turn.complete);
function inputs(refills){let seed=refills[0].private_seed;const initial=seed,events=[],starts=[];for(const f of refills){assert.equal(f.private_seed,seed);starts.push(be32(f.stack_ticks));for(const event of f.events){if(event.kind==='private_random'){seed=(seed>>>1)+((((seed>>>4)^seed)&1)*0x40000000);assert.equal(seed,event.value);}else events.push(Buffer.concat([be32(event.kind==='ticks'?0:1),be32(event.value)]));}assert.equal(seed,f.final.private_seed);}return{initial,final:seed,events:Buffer.concat(events),starts:Buffer.concat(starts),count:events.length,refills:refills.length};}
const h=inputs(history.refills),g=inputs(turn.turn.refills),original=Buffer.from(history.wire,'hex');
write(8,original);write(6,h.events);write(7,h.starts);const heap=e.maven_port_count(12);
for(let repeat=0;repeat<20;repeat++){
 assert.equal(e.maven_port_load(original.length,h.initial,h.count,h.refills),0);assert.equal(e.maven_port_count(12),heap,'temporary import memory released');assert.equal(e.maven_port_count(7),h.final);assert.equal(e.maven_port_count(8),h.count);assert.equal(e.maven_port_count(9),h.refills);assert.equal(e.maven_port_count(11),33);
}
assert.equal(e.maven_port_get_position(),0);const finished=read(2,477);assert.equal(finished[476],2);assert.equal(finished[450],0);assert.equal(finished[458],0);
assert.equal(e.maven_port_save(),0);assert.deepEqual(read(8,e.maven_port_count(10)),original);
write(8,original.subarray(0,original.length-1));assert.equal(e.maven_port_load(original.length-1,h.initial,h.count,h.refills),1);assert.equal(e.maven_port_get_position(),0);assert.deepEqual(read(2,477),finished);
assert.equal(e.maven_port_history_select(26,h.final,0,0),0);assert.equal(e.maven_port_get_position(),0);const before=read(2,477);assert.equal(e.maven_port_count(11),33);
function position(s,side){const b=Buffer.from(s.board,'hex'),v=Buffer.from(s.values,'hex'),p=Buffer.alloc(477);for(let r=1;r<16;r++)for(let c=1;c<16;c++){const k=r*17+c,i=(r-1)*15+c-1;p[i]=b[k];p[i+225]=+(!!b[k]&&!v.readUInt16BE(2*k));}Buffer.from(s.rack0,'hex').copy(p,450);Buffer.from(s.rack1,'hex').copy(p,458);p.writeUInt32BE(s.totals[0],466);p.writeUInt32BE(s.totals[1],470);p.writeUInt16BE(s.row_zero_count,474);p[476]=side;return p;}
assert.deepEqual(before,position(turn.turn.initial,0));assert.equal(e.maven_port_late(1,0),0);const ranking=read(3,340);let index=-1;for(let i=0;i<e.maven_port_count(0);i++){const m=ranking.subarray(i*34,(i+1)*34);if(m.subarray(0,16).toString().split('\0')[0]==='burin'&&m[32]===17&&m[33]===2){index=i;break;}}assert(index>=0);
view(9).fill(0x5a);const unchanged=read(9,314),savedSeed=e.maven_port_count(7);write(6,g.events);
assert.equal(e.maven_port_play(index,g.initial,turn.turn.refills[0].stack_ticks,0),7);assert.deepEqual(read(9,314),unchanged);assert.equal(e.maven_port_count(7),savedSeed);assert.equal(e.maven_port_count(11),33);assert.equal(e.maven_port_get_position(),0);assert.deepEqual(read(2,477),before);
assert.equal(e.maven_port_play(index,g.initial,turn.turn.refills[0].stack_ticks,g.count),0);assert.equal(e.maven_port_count(7),g.final);assert.equal(e.maven_port_count(8),g.count);assert.equal(e.maven_port_count(11),36);
const result=read(9,314);assert.deepEqual(result.subarray(0,34),Buffer.from(turn.move,'hex'));assert.deepEqual(result.subarray(34,122),Buffer.concat(turn.turn.final.features.map(be32)));assert.equal(result.readUInt32BE(298),turn.result_bits);assert.equal(result.readUInt32BE(302),1);assert.equal(result.readUInt32BE(306),2);
assert.equal(e.maven_port_get_position(),0);assert.deepEqual(read(2,477),position(turn.turn.final,1));assert.equal(e.maven_port_play(index,g.initial,0,g.count),1,'ranking invalidated');
assert.equal(e.maven_port_save(),0);const saved=read(8,e.maven_port_count(10));assert.deepEqual(saved.subarray(0,original.length),original,'old future retained');
write(6,g.events);write(7,g.starts);assert.equal(e.maven_port_load(saved.length,g.initial,g.count,1),0);assert.equal(e.maven_port_get_position(),0);assert.deepEqual(read(2,477),position(turn.turn.final,0),'original Open restores human orientation');assert.equal(e.maven_port_count(12),heap);
assert.equal(e.maven_port_save(),0);assert.deepEqual(read(8,e.maven_port_count(10)),saved);
console.log(JSON.stringify({scope:'Owned wasm original file load/history selection/search/BURIN commit/save/reload',repeated_loads:20,temporary_allocation_released:true,records:36,failed_callback_atomic:true,all_matched:true,wasm_sha256:crypto.createHash('sha256').update(wasm).digest('hex')}));
